### PR TITLE
Task honey shipper solidity

### PR DESCRIPTION
**Pull request by honey93**
Added smart Contract SupplychainContract.sol in the contractSandbox folder.

### CODE REVIEW

**Comment by pcppcp** [comment]
please fix the file permissions before merging this (they should be 0644)

**Comment by honey93** [comment]
Used the following command to turn it off. See if it works   @@!!
git config --local core.fileMode false

**Comment by lorepieri8** [comment]
@honey93  the file still have the same wrong permission. Maybe `git reset` to previous commit, add the two files and push again? Is a problem of your machine?

**Comment by honey93** [comment]
Hi Team,
Did changes in file permission as well as removed sudo usage while pushing the code. Do check if it works now??

**Comment by lorepieri8** [comment]
If you go to the overall file changes, the permission changes are still there. Redo the push request from scratch: clone, copy paste your new files and push. That should work I guess.

**Pull request closed without merging**
